git submodule add https://github.com/itchyny/lightline.vim
git submodule add https://github.com/vim-syntastic/syntastic.git
git submodule add https://github.com/tpope/vim-commentary.git
git submodule add https://github.com/tpope/vim-repeat.git
git submodule add https://github.com/godlygeek/tabular.git
git submodule add https://github.com/nanotech/jellybeans.vim.git
git submodule add https://github.com/KeyboardFire/vim-minisnip.git
git submodule add https://github.com/tpope/vim-surround.git
git submodule add https://github.com/tpope/vim-ragtag.git
